# Generated by Django 4.2.11 on 2024-04-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("ingredients", models.TextField()),
                ("cooking_time", models.FloatField()),
                ("difficulty", models.TextField()),
            ],
        ),
    ]
