# Generated by Django 4.2.11 on 2024-04-23 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipes",
            name="pic",
            field=models.ImageField(default="no_picture.jpg", upload_to="Recipes"),
        ),
    ]
