# Generated by Django 4.2.11 on 2024-08-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0002_recipes_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='difficulty',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='pic',
            field=models.ImageField(default='no_picture.jpg', upload_to='Recipes'),
        ),
    ]
